# Site settings
title: Lovel
email: lovel_trh@outlook.com
description: >
  Lovel.no, elektriker Trondheim
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lovel.no" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
